### ISSUE TITLE
Syntax error when used with genesis theme

### ISSUE THREAD

**Issue by admorgan** [octopress/social#1]
When generating a new site I get this error.

/home/admorgan/.gem/ruby/1.9.1/gems/octopress-social-1.4.2/lib/octopress-social.rb:39:in `<top (required)>': /home/admorgan/.gem/ruby/1.9.1/gems/octopress-social-1.4.2/lib/octopress-social/twitter.rb:108: invalid multibyte char (US-ASCII) (SyntaxError)
/home/admorgan/.gem/ruby/1.9.1/gems/octopress-social-1.4.2/lib/octopress-social/twitter.rb:104: invalid multibyte char (US-ASCII)
/home/admorgan/.gem/ruby/1.9.1/gems/octopress-social-1.4.2/lib/octopress-social/twitter.rb:104: syntax error, unexpected $end, expecting keyword_end
          <a href="#{url}"> — #{user}</a>
                              ^

I don't see a problem with the code. This happens even when I don't include twitter in the share options.

**Comment by imathis** [comment]
Ah, you're on ruby 1.9. I may need to be explicit about a uff-8 encoding. Thanks. I'll work on getting a fix out.

**Comment by imathis** [comment]
I've just released Octopress Social 1.4.3 which should prevent the US-ASCII issue you're experiencing. Please run `bundle update` and let me know if that helps.

**Comment by admorgan** [comment]
That fixed my issue.

**Comment by imathis** [comment]
Excellent! Thanks for the report!
